config/routes.rb
Rails.application.routes.draw do

  get 'homepage/index'
  get 'homepage' => 'homepage#index'
  get 'index' => 'homepage#index'
  get '/' => 'homepage#index'
  post 'fotos/new' => 'fotos#new'
  resources :fotos
  get 'signup'  => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'pages/login' => 'sessions#new'
  get 'pages/signup' => 'users#new'
  post 'homepage' => 'homepage#index'
  resources :users

  root 'homepage#index'
end

app/models/foto.rb
class Foto < ActiveRecord::Base
  belongs_to :user
  has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "400x300" },
                    :storage => :ftp,
                    # Set where to store the file on the FTP server(s).
                    # This supports Paperclip::Interpolations.
                    :path => "/public_html/:attachment/:id/:style/:filename",

                    # The full URL of where the attachment is publicly accessible.
                    # This supports Paperclip::Interpolations.
                    :url => "http://fotasia.16mb.com/:attachment/:id/:style/:filename",

                    # The list of FTP servers to use
                    :ftp_servers => [
                        {
                            :host     => ENV["HOST"],
                            :user     => ENV["USER"],
                            :password => ENV["PASSWORD"],
                            :port => 21,
                            :passive  => true
                        }]
  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :fotos
  has_secure_password
  validates :username, presence: true
  validates :email, presence: true
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  require 'paperclip/storage/ftp'
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  def require_user
    redirect_to '/login' unless current_user
  end
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :foto_all
  def foto_all
    @fotos = Foto.all
  end
  helper_method :user_all
  def user_all
    @users = User.all
  end
end

app/controllers/fotos_controller.rb
class FotosController < ApplicationController
  before_action :require_user, only: [:index, :show]
  before_action :set_foto, only: [:show]


  # GET /fotos
  # GET /fotos.json
  def index
    @fotos = Foto.all
    @users = User.all
  end

  # GET /fotos/1
  # GET /fotos/1.json
  def show
  end

  # GET /fotos/new
  def new
    @foto = Foto.new
  end

  # GET /fotos/1/edit
  def edit
  end

  # POST /fotos
  # POST /fotos.json
  def create
    @foto = Foto.new(foto_params)

    respond_to do |format|
      if @foto.save
        format.html { redirect_to @foto, notice: 'Foto was successfully created.' }
        format.json { render :show, status: :created, location: @foto }
      else
        format.html { render :new }
        format.json { render json: @foto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fotos/1
  # PATCH/PUT /fotos/1.json
  def update
    respond_to do |format|
      if @foto.update(foto_params)
        format.html { redirect_to @foto, notice: 'Foto was successfully updated.' }
        format.json { render :show, status: :ok, location: @foto }
      else
        format.html { render :edit }
        format.json { render json: @foto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fotos/1
  # DELETE /fotos/1.json
  def destroy
    @foto.destroy
    respond_to do |format|
      format.html { redirect_to fotos_url, notice: 'Foto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_foto
    @foto = Foto.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def foto_params
    params.require(:foto).permit(:id, :title, :date, :content, :user_id, :username, :image)
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    @user = User.find_by_email(params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to '/'
    else
      redirect_to '/login'
    end
  end
  def destroy
    session[:user_id] = nil
    redirect_to '/'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user, only: [:index, :show]
  before_action :set_user, only: [:show]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end
  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end
  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fotos_helper.rb
module FotosHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/fotos/_form.html.erb
<%= form_for @foto, html: { multipart: true } do |f| %>
    <% if @foto.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@foto.errors.count, "error") %> prohibited this foto from being saved:</h2>

          <ul>
            <% @foto.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :title %><br>
      <%= f.text_area :title %>
    </div>
    <div class="field">
      <%= f.label :date %><br>
      <%= f.date_select :date %>
    </div>
    <div class="field">
      <%= f.label :content %><br>
      <%= f.text_area :content %>
    </div>
    <div class="field">
      <i><%= f.hidden_field :username, :value => current_user.username %></i><br>
    </div>
    <div class="field">
      <i><%= f.label "Choose image" %></i>
      <%= f.file_field :image %>
    </div><br>
    <center><div class="actions">
      <%= f.submit class: "btn-submit"  %>
    </div></center><br>
<% end %>

app/views/fotos/edit.html.erb
<% provide(:title, "Foto Edit") %>
<center><h1>Editing Foto</h1></center>

<center><%= render 'form' %></center>

<center><%= button_to 'Show', @foto, class: "btn-normal" %>
  <%= button_to 'Back', fotos_path, class: "btn-normal" %></center>

app/views/fotos/index.html.erb
<% provide(:title, "Fotos") %>
<center><table>
  <tbody>
  <% @fotos.each do |foto| %>
      <tr>
        <td><%= foto.title %></td>
        <td><%= foto.date %></td>
        <td><%= foto.content %></td>
        <td><%= foto.user_id %></td>
        <td><%= foto.username %></td>
        <td><%= foto.image %></td>
        <td><%= link_to 'Show', foto, class: "btn-small" %></td>
        <td><%= link_to 'Edit', foto, method: :edit, class: "btn-small" %></td>
        <td><%= link_to 'Destroy', foto, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn-small" %></td>
      </tr>
  <% end %>
  </tbody>
</table></center>

<br>

<center><%= button_to 'New Foto', new_foto_path, class: "btn-submit" %></center>

app/views/fotos/new.html.erb
<% provide(:title, "Foto new") %>
<center><h1>Add Foto</h1></center>

<center><%= render 'form' %></center>

<center><%= button_to 'Back', homepage_path, class: "btn-normal" %></center>

app/views/fotos/show.html.erb
<% provide(:title, "Foto") %>
<p>
  <strong>Title:</strong>
  <%= @foto.title %>
</p>

<p>
  <strong>Date:</strong>
  <%= @foto.date %>
</p>

<p>
  <strong>Content:</strong>
  <%= @foto.content %>
</p>

<p>
  <strong>Username:</strong>
  <%= @foto.username %>
</p>

<h1><%= link_to image_tag(@foto.image.url(:med)), @foto.image.url %></h1>

<%= link_to 'Edit', edit_foto_path, class: "btn-normal" %>
<%= link_to 'Back', homepage_path, class: "btn-normal" %>

app/views/homepage/index.html.erb
<% provide(:title, "Homepage") %>
<style></head><body><h1> style="text-align: center; font-family: Abyssinica SIL;">Fotasia Hompage<br>
</h1></body></style>
<div style="text-align: center;"><img src="/images/fotasia.jpg" alt="Fotasia Album Website" style="width: 286px; height: 286px;" align="top">
  <!DOCTYPE html>
</div>
<!-- Page Content -->
<div class="container">

  <div class="row">

    <div class="col-lg-12">
      <h1 class="page-header">Foto Galery</h1>
    </div>
        <% foto_all.each do |foto|%>
            <div class="col-lg-3 col-md-4 col-xs-6 thumb">
              <a class="thumbnail" href=<%=foto.image.url%> data-toggle="tooltip" title="User:  <%= foto.username %>
      &#10;Title:  <%= foto.title %>
     &#10;Date_Created:  <%= foto.date %>">
                <img class="img-responsive" src=<%= foto.image%>>
                <p><%= foto.content %></p>
              </a>
            </div>
        <% end %>
    <hr>

    <!-- Footer -->
    <footer>
      <div class="row">
        <div class="col-lg-12">
          <p>Copyright &copy; K.O Website 2015</p>
        </div>
      </div>
    </footer>
  </div>
</div>
<!-- /.container -->

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
      <% if current_user %>
          <%= link_to 'New Foto', new_foto_url, class: 'navbar-brand' %>
          <div style="color:forestgreen", class="navbar-brand">
              <%= current_user.email %>  </div>
          <%= link_to "Log out", logout_path, method: "delete",data: { confirm: 'Log out! Are you sure?' }, class: 'navbar-brand' %>
      <% else %>
          <%= link_to "Login", '/login', class: 'navbar-brand' %>
          <%= link_to "Signup", 'signup', class: 'navbar-brand' %>
      <% end %>

    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%= link_to 'About', page_path('about'), class: 'navbar-brand' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= yield(:title) %> | Fotasia </title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Bootstrap Test" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <div class="nav center-block"></div>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<% provide(:title, "About") %>
<center><h3>About the Website</h3></center>
<center>
  <div style="text-align: center;"><img src="/images/fotasia_logo.jpg" alt="Fotasia Album Website" style="width: 486px; height: 286px;" align="top"></div>
  <p><b><%= render text: "Foto Web App v.0.3.1 alpha " %></b>
</p></center>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
    <div class="login">
      <div class="container">
        <div class="form">
          <%= f.label :username %>
          <%= f.text_field :username, :placeholder => "Username"%><br>
          <%= f.label :email %>
          <%= f.text_field :email, :placeholder => "Email" %><br>
          <%= f.label :password %>
          <%= f.password_field :password, :placeholder => "Password" %><br>
        </div>
      </div>
    </div>
    <center><div><%= f.submit "Create an account", class: "btn-submit" %></div></center><br>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "User Edit") %>
<center><h1>Editing User</h1></center>

<center><%= render 'form' %></center>

<center><%= button_to 'Show', @user, class: "btn-normal" %> |</center>
<center><%= button_to 'Back', homepage_path, class: "btn-normal" %></center>

app/views/users/index.html.erb
<% provide(:title, "Users") %>
<h1>Listing Users</h1>

<table>
  <thead>
  <tr>
    <th>Username</th>
    <th>Email</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<% provide(:title, "Signup") %>
<center><h1>New User</h1></center>

<%= render 'form' %>

<center><%= button_to 'Back', homepage_url, class: "btn-normal" %></center>

app/views/users/show.html.erb
<% provide(:title, "Show User") %>
<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>


<%= button_to 'Edit', edit_user_path(@user), class: "btn-normal" %>
<%= button_to 'Back', homepage_path, class: "btn-normal" %>